# Generated by Django 4.2.2 on 2023-06-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='perecent',
            new_name='percent',
        ),
    ]
